# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./main.go

    - name: Test
      run: go test -v ./...
    - uses: actions/checkout@v4
      with:
        repository: 'https://github.com/webra2/webra2.github.io'
        path: website
    - name: download
      run: ./main -u https://game.chronodivide.com
    - name: push
      run: |
        cd webiste
        ls website -R -l
        git config --local user.email "webra2@webra2.com"
        git config --local user.name "webra2"
        git commit -a -m "Add changes"
        git push origin main
    
